name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 0) リポジトリをチェックアウト ← これが必須
      - uses: actions/checkout@v4

      # 1) ツールチェーンをインストール
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-none-eabi \
            cppcheck \
            clang-tidy

      # 2) ダミーをビルド（-c でコンパイルのみ）
      - name: Build dummy
        run: |
          mkdir -p build
          arm-none-eabi-gcc -Wall -Werror -mcpu=cortex-m4 -mthumb \
            -c tests/dummy/main.c -o build/main.o

      # 3) 静的解析
      - name: Static analysis
        run: |
          cppcheck --enable=all --std=c11 tests/dummy

